# Constants
SCALE = 1
SCENE_SYSTEM = 'METRIC'
SCENE_UNITS = 'MILLIMETERS'

QR_CODE_SIZE = 20
QR_SPACING = 0
QR_CODE_THICKNESS = .2
QUIET_ZONE = 8

BASEPLATE_THICKNESS = .2

TEXT_FILE_NAME = 'blockbit.ttf'



GRID_SIZE = 2
FONT_SIZE = 6
TEXT_X_OFFSET = 4
TEXT_Y_OFFSET = -1
INVERT_QR_CODE = True